# Barcelona GP 2025 - Results and Lap Data Analysis

In [3]:
import fastf1
import pandas

In [4]:
#Session Import and Load
session = fastf1.get_session(
    2025,
    "Spanish Grand Prix",
    "Q"
)
session.load()

req         WARNING 	DEFAULT CACHE ENABLED! (24.0 KB) /home/decoder_linux/.cache/fastf1
core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '1', '63', '44', '12', '16', '10', '6', '14', '23', '5', '30', '18', '87', '27', '31', '55', '43', '22']

In [6]:
#Column Inspection
print(f"Reults Column: {session.results.columns}")
print(f"Laps Column: {session.laps.columns}")

Reults Column: Index(['DriverNumber', 'BroadcastName', 'Abbreviation', 'DriverId', 'TeamName',
       'TeamColor', 'TeamId', 'FirstName', 'LastName', 'FullName',
       'HeadshotUrl', 'CountryCode', 'Position', 'ClassifiedPosition',
       'GridPosition', 'Q1', 'Q2', 'Q3', 'Time', 'Status', 'Points', 'Laps'],
      dtype='object')
Laps Column: Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')

### Results column:
- Q1
- Q2
- Q3
- Time
- Status
- Points
- Laps

### Laps Column:
- Most of the columns are need!

In [8]:
#Results with Qualifying timings
results = session.results[[
    "Position",
    "Abbreviation",
    "TeamName",
    "Q1",
    "Q2",
    "Q3"
]]

results

,Position,Abbreviation,TeamName,Q1,Q2,Q3
81,1.0,PIA,McLaren,0 days 00:01:12.551000,0 days 00:01:11.998000,0 days 00:01:11.546000
4,2.0,NOR,McLaren,0 days 00:01:12.799000,0 days 00:01:12.056000,0 days 00:01:11.755000
1,3.0,VER,Red Bull Racing,0 days 00:01:12.798000,0 days 00:01:12.358000,0 days 00:01:11.848000
63,4.0,RUS,Mercedes,0 days 00:01:12.806000,0 days 00:01:12.407000,0 days 00:01:11.848000
44,5.0,HAM,Ferrari,0 days 00:01:13.058000,0 days 00:01:12.447000,0 days 00:01:12.045000
12,6.0,ANT,Mercedes,0 days 00:01:12.815000,0 days 00:01:12.585000,0 days 00:01:12.111000
16,7.0,LEC,Ferrari,0 days 00:01:13.014000,0 days 00:01:12.495000,0 days 00:01:12.131000
10,8.0,GAS,Alpine,0 days 00:01:13.081000,0 days 00:01:12.611000,0 days 00:01:12.199000
6,9.0,HAD,Racing Bulls,0 days 00:01:13.139000,0 days 00:01:12.461000,0 days 00:01:12.252000
14,10.0,ALO,Aston Martin,0 days 00:01:13.102000,0 days 00:01:12.523000,0 days 00:01:12.284000
23,11.0,ALB,Williams,0 days 00:01:13.044000,0 days 00:01:12.641000,NaT
5,12.0,BOR,Kick Sauber,0 days 00:01:13.045000,0 days 00:01:12.756000,NaT
30,13.0,LAW,Racing Bulls,0 days 00:01:13.039000,0 days 00:01:12.763000,NaT
18,14.0,STR,Aston Martin,0 days 00:01:13.038000,0 days 00:01:13.058000,NaT
87,15.0,BEA,Haas F1 Team,0 days 00:01:13.074000,0 days 00:01:13.315000,NaT
27,16.0,HUL,Kick Sauber,0 days 00:01:13.190000,NaT,NaT
31,17.0,OCO,Haas F1 Team,0 days 00:01:13.201000,NaT,NaT
55,18.0,SAI,Williams,0 days 00:01:13.203000,NaT,NaT
43,19.0,COL,Alpine,0 days 00:01:13.334000,NaT,NaT
22,20.0,TSU,Red Bull Racing,0 days 00:01:13.385000,NaT,NaT

In [9]:
#Examine Laps data
laps = session.laps

laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:21:40.660000,PIA,81,NaT,1.0,1.0,0 days 00:19:36.751000,NaT,NaT,0 days 00:00:37.085000,...,True,McLaren,0 days 00:19:36.751000,2025-05-31 14:06:06.394,1,NaN,False,,False,False
1,0 days 00:22:53.211000,PIA,81,0 days 00:01:12.551000,2.0,1.0,NaT,NaT,0 days 00:00:21.477000,0 days 00:00:29.062000,...,True,McLaren,0 days 00:21:40.660000,2025-05-31 14:08:10.303,1,NaN,False,,False,True
2,0 days 00:24:36.804000,PIA,81,0 days 00:01:43.593000,3.0,1.0,NaT,0 days 00:24:34.189000,0 days 00:00:34.596000,0 days 00:00:37.166000,...,True,McLaren,0 days 00:22:53.211000,2025-05-31 14:09:22.854,1,NaN,False,,False,False
3,0 days 00:28:53.745000,PIA,81,NaT,4.0,2.0,0 days 00:26:59.708000,NaT,NaT,0 days 00:00:38.614000,...,False,McLaren,0 days 00:24:36.804000,2025-05-31 14:11:06.447,1,NaN,False,,False,False
4,0 days 00:30:49.757000,PIA,81,0 days 00:01:56.012000,5.0,2.0,NaT,0 days 00:30:15.930000,0 days 00:00:21.784000,0 days 00:00:31.625000,...,False,McLaren,0 days 00:28:53.745000,2025-05-31 14:15:23.388,1,NaN,False,,False,False

In [13]:
# Lap count
print(f"Total Lap Data Avilable = {len(laps)}")
print(f"Accurate Lap Data = {len(laps[laps["IsAccurate"] == True])}")

Total Lap Data Avilable = 247
Accurate Lap Data = 78

In [ ]:
#Drivers available in the session
laps["Driver"].unique()

array(['PIA', 'NOR', 'VER', 'RUS', 'HAM', 'ANT', 'LEC', 'GAS', 'HAD',
       'ALO', 'ALB', 'BOR', 'LAW', 'STR', 'BEA', 'HUL', 'OCO', 'SAI',
       'COL', 'TSU'], dtype=object)

In [ ]:
#Driver Specific Data
#1. Max Verstappen
max = laps.pick_drivers("VER")
max

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
29,0 days 00:23:21.610000,VER,1,NaT,1.0,1.0,0 days 00:21:16.971000,NaT,NaT,0 days 00:00:41.544000,...,True,Red Bull Racing,0 days 00:21:16.971000,2025-05-31 14:07:46.614,1,NaN,False,,False,False
30,0 days 00:24:34.408000,VER,1,0 days 00:01:12.798000,2.0,1.0,NaT,NaT,0 days 00:00:21.612000,0 days 00:00:29.189000,...,True,Red Bull Racing,0 days 00:23:21.610000,2025-05-31 14:09:51.253,1,NaN,False,,False,True
31,0 days 00:26:19.808000,VER,1,0 days 00:01:45.400000,3.0,1.0,NaT,0 days 00:26:17.009000,0 days 00:00:30.480000,0 days 00:00:42.479000,...,True,Red Bull Racing,0 days 00:24:34.408000,2025-05-31 14:11:04.051,1,NaN,False,,False,False
32,0 days 00:42:33.380000,VER,1,NaT,4.0,2.0,0 days 00:40:53.063000,NaT,NaT,0 days 00:00:42.293000,...,True,Red Bull Racing,0 days 00:26:19.808000,2025-05-31 14:12:49.451,1,NaN,False,,False,False
33,0 days 00:43:45.738000,VER,1,0 days 00:01:12.358000,5.0,2.0,NaT,NaT,0 days 00:00:21.617000,0 days 00:00:28.898000,...,True,Red Bull Racing,0 days 00:42:33.380000,2025-05-31 14:29:03.023,1,NaN,False,,False,True
34,0 days 00:45:53.219000,VER,1,0 days 00:02:07.481000,6.0,2.0,NaT,0 days 00:45:24.839000,0 days 00:00:30.517000,0 days 00:00:40,...,True,Red Bull Racing,0 days 00:43:45.738000,2025-05-31 14:30:15.381,1,NaN,False,,False,False
35,0 days 01:04:25.493000,VER,1,NaT,7.0,3.0,0 days 01:02:35.503000,NaT,NaT,0 days 00:00:37.875000,...,True,Red Bull Racing,0 days 00:45:53.219000,2025-05-31 14:32:22.862,1,NaN,False,,False,False
36,0 days 01:05:37.814000,VER,1,0 days 00:01:12.321000,8.0,3.0,NaT,NaT,0 days 00:00:21.454000,0 days 00:00:29.047000,...,True,Red Bull Racing,0 days 01:04:25.493000,2025-05-31 14:50:55.136,1,NaN,False,,False,True
37,0 days 01:07:20.101000,VER,1,0 days 00:01:42.287000,9.0,3.0,NaT,0 days 01:07:17.495000,0 days 00:00:28.333000,0 days 00:00:39.712000,...,True,Red Bull Racing,0 days 01:05:37.814000,2025-05-31 14:52:07.457,1,NaN,False,,False,False
38,0 days 01:13:03.089000,VER,1,NaT,10.0,4.0,0 days 01:11:01.276000,NaT,NaT,0 days 00:00:41.548000,...,True,Red Bull Racing,0 days 01:07:20.101000,2025-05-31 14:53:49.744,1,NaN,False,,False,False
39,0 days 01:14:14.937000,VER,1,0 days 00:01:11.848000,11.0,4.0,NaT,NaT,0 days 00:00:21.464000,0 days 00:00:28.704000,...,True,Red Bull Racing,0 days 01:13:03.089000,2025-05-31 14:59:32.732,1,NaN,False,,False,True
40,0 days 01:15:59.175000,VER,1,NaT,12.0,4.0,NaT,0 days 01:15:59.175000,0 days 00:00:33.824000,0 days 00:00:38.702000,...,True,Red Bull Racing,0 days 01:14:14.937000,2025-05-31 15:00:44.580,1,NaN,False,,False,False

In [18]:
#2. Charles Leclerc
leclerc = laps.pick_drivers("LEC")
leclerc

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
86,0 days 00:22:28.847000,LEC,16,NaT,1.0,1.0,0 days 00:20:38.742000,NaT,NaT,0 days 00:00:39.030000,...,True,Ferrari,0 days 00:20:38.742000,2025-05-31 14:07:08.385,1,NaN,False,,False,False
87,0 days 00:23:41.861000,LEC,16,0 days 00:01:13.014000,2.0,1.0,NaT,NaT,0 days 00:00:21.673000,0 days 00:00:29.184000,...,True,Ferrari,0 days 00:22:28.847000,2025-05-31 14:08:58.490,1,NaN,False,,False,True
88,0 days 00:25:57.770000,LEC,16,0 days 00:02:15.909000,3.0,1.0,NaT,0 days 00:25:21.892000,0 days 00:00:28.617000,0 days 00:00:38.250000,...,True,Ferrari,0 days 00:23:41.861000,2025-05-31 14:10:11.504,1,NaN,False,,False,False
89,0 days 00:31:16.822000,LEC,16,NaT,4.0,2.0,0 days 00:28:48.581000,0 days 00:31:13.972000,NaT,0 days 00:00:38.273000,...,True,Ferrari,0 days 00:25:57.770000,2025-05-31 14:12:27.413,1,NaN,False,,False,False
90,0 days 00:44:12.525000,LEC,16,NaT,5.0,3.0,0 days 00:42:12.187000,NaT,NaT,0 days 00:00:41.192000,...,True,Ferrari,0 days 00:31:16.822000,2025-05-31 14:17:46.465,1,NaN,False,,False,False
91,0 days 00:45:25.020000,LEC,16,0 days 00:01:12.495000,6.0,3.0,NaT,NaT,0 days 00:00:21.501000,0 days 00:00:28.955000,...,True,Ferrari,0 days 00:44:12.525000,2025-05-31 14:30:42.168,1,NaN,False,,False,True
92,0 days 00:47:01.985000,LEC,16,0 days 00:01:36.965000,7.0,3.0,NaT,0 days 00:46:59.191000,0 days 00:00:28.235000,0 days 00:00:36.347000,...,True,Ferrari,0 days 00:45:25.020000,2025-05-31 14:31:54.663,1,NaN,False,,False,False
93,0 days 00:53:17.058000,LEC,16,NaT,8.0,4.0,0 days 00:51:23.531000,NaT,NaT,0 days 00:00:38.458000,...,False,Ferrari,0 days 00:47:01.985000,2025-05-31 14:33:31.628,1,NaN,False,,False,False
94,0 days 00:54:40.282000,LEC,16,0 days 00:01:23.224000,9.0,4.0,NaT,0 days 00:54:37.490000,0 days 00:00:21.654000,0 days 00:00:29.354000,...,False,Ferrari,0 days 00:53:17.058000,2025-05-31 14:39:46.701,1,NaN,False,,False,False
95,0 days 01:05:59.577000,LEC,16,NaT,10.0,5.0,0 days 01:04:18.585000,NaT,NaT,0 days 00:00:40.574000,...,True,Ferrari,0 days 00:54:40.282000,2025-05-31 14:41:09.925,1,NaN,False,,False,False
96,0 days 01:07:11.708000,LEC,16,0 days 00:01:12.131000,11.0,5.0,NaT,NaT,0 days 00:00:21.458000,0 days 00:00:28.729000,...,True,Ferrari,0 days 01:05:59.577000,2025-05-31 14:52:29.220,1,NaN,False,,False,True
97,0 days 01:08:42.129000,LEC,16,0 days 00:01:30.421000,12.0,5.0,NaT,0 days 01:08:39.334000,0 days 00:00:25.589000,0 days 00:00:34.185000,...,True,Ferrari,0 days 01:07:11.708000,2025-05-31 14:53:41.351,1,NaN,False,,False,False

In [19]:
# Max and Leclerc Tyre Ages
print("Max and Leclerc Fresh Tyre Period:")
print(f"Max Verstappen = {len(max[max["FreshTyre"] == True])}")
print(f"Charles Leclerc = {len(leclerc[leclerc["FreshTyre"] == True])}")

Max and Leclerc Fresh Tyre Period:
Max Verstappen = 12
Charles Leclerc = 10

In [20]:
#Fastest Lap
fastest_lap = laps.pick_fastest()
fastest_lap

Time                      0 days 01:13:39.533000
Driver                                       PIA
DriverNumber                                  81
LapTime                   0 days 00:01:11.546000
LapNumber                                   13.0
Stint                                        5.0
PitOutTime                                   NaT
PitInTime                                    NaT
Sector1Time               0 days 00:00:21.259000
Sector2Time               0 days 00:00:28.580000
Sector3Time               0 days 00:00:21.707000
Sector1SessionTime        0 days 01:12:49.246000
Sector2SessionTime        0 days 01:13:17.826000
Sector3SessionTime        0 days 01:13:39.533000
SpeedI1                                    294.0
SpeedI2                                    311.0
SpeedFL                                    297.0
SpeedST                                    326.0
IsPersonalBest                              True
Compound                                    SOFT
TyreLife                                     2.0
FreshTyre                                   True
Team                                     McLaren
LapStartTime              0 days 01:12:27.987000
LapStartDate          2025-05-31 14:58:57.630000
TrackStatus                                    1
Position                                     NaN
Deleted                                    False
DeletedReason
FastF1Generated                            False
IsAccurate                                  True
Name: 12, dtype: object

In [ ]:
# Deep examine
fastest_lap[["Driver","LapTime"]]