# **Austria GP 2026**
## Results and Lap Analysis

In [56]:
# Imports
import sys
import importlib
sys.path.append("../..")

import Sliplib.slipload as sl
import Sliplib.selection as slipclassify

importlib.reload(slipclassify)

In [57]:
# Load Session
session_Q = sl.load_gp(2025,"Austrian Grand Prix","Q")
session_Q.load()

core           INFO 	Loading data for Austrian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '16'
core        WARNING 	Fixed incorrect tyre stint information for driver '1'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
core        WARNING 	Fixed incorrect tyre stint information for driver '12'
core        WARNING 	Fixed incorrect tyre stint information for driver '10'
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
core        WARNING 	Fixed incorrect tyre stint information for driver '6'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '16', '81', '44', '63', '30', '1', '5', '12', '10', '14', '23', '6', '43', '87', '18', '31', '22', '55', '27']

### Result Inspection
Inspect Results of Qualifying Sessions

In [58]:
# Import Session Result
ses_res = session_Q.results
ses_res

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
4,4,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,1.0,,NaN,0 days 00:01:04.672000,0 days 00:01:04.410000,0 days 00:01:03.971000,NaT,,NaN,NaN
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,2.0,,NaN,0 days 00:01:05.197000,0 days 00:01:04.734000,0 days 00:01:04.492000,NaT,,NaN,NaN
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,3.0,,NaN,0 days 00:01:04.966000,0 days 00:01:04.556000,0 days 00:01:04.554000,NaT,,NaN,NaN
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,4.0,,NaN,0 days 00:01:05.115000,0 days 00:01:04.896000,0 days 00:01:04.582000,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,5.0,,NaN,0 days 00:01:05.189000,0 days 00:01:04.860000,0 days 00:01:04.763000,NaT,,NaN,NaN
30,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,6.0,,NaN,0 days 00:01:05.017000,0 days 00:01:05.041000,0 days 00:01:04.926000,NaT,,NaN,NaN
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,7.0,,NaN,0 days 00:01:05.106000,0 days 00:01:04.836000,0 days 00:01:04.929000,NaT,,NaN,NaN
5,5,G BORTOLETO,BOR,bortoleto,Kick Sauber,01C00E,sauber,Gabriel,Bortoleto,Gabriel Bortoleto,...,8.0,,NaN,0 days 00:01:05.123000,0 days 00:01:04.846000,0 days 00:01:05.132000,NaT,,NaN,NaN
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,9.0,,NaN,0 days 00:01:05.178000,0 days 00:01:05.052000,0 days 00:01:05.276000,NaT,,NaN,NaN
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,10.0,,NaN,0 days 00:01:05.054000,0 days 00:01:04.846000,0 days 00:01:05.649000,NaT,,NaN,NaN
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,11.0,,NaN,0 days 00:01:05.197000,0 days 00:01:05.128000,NaT,NaT,,NaN,NaN
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,12.0,,NaN,0 days 00:01:05.143000,0 days 00:01:05.205000,NaT,NaT,,NaN,NaN
6,6,I HADJAR,HAD,hadjar,Racing Bulls,6C98FF,rb,Isack,Hadjar,Isack Hadjar,...,13.0,,NaN,0 days 00:01:05.063000,0 days 00:01:05.226000,NaT,NaT,,NaN,NaN
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,14.0,,NaN,0 days 00:01:05.278000,0 days 00:01:05.288000,NaT,NaT,,NaN,NaN
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,15.0,,NaN,0 days 00:01:05.218000,0 days 00:01:05.312000,NaT,NaT,,NaN,NaN
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,16.0,,NaN,0 days 00:01:05.329000,NaT,NaT,NaT,,NaN,NaN
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,17.0,,NaN,0 days 00:01:05.364000,NaT,NaT,NaT,,NaN,NaN
22,22,Y TSUNODA,TSU,tsunoda,Red Bull Racing,4781D7,red_bull,Yuki,Tsunoda,Yuki Tsunoda,...,18.0,,NaN,0 days 00:01:05.369000,NaT,NaT,NaT,,NaN,NaN
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,19.0,,NaN,0 days 00:01:05.582000,NaT,NaT,NaT,,NaN,NaN
27,27,N HULKENBERG,HUL,hulkenberg,Kick Sauber,01C00E,sauber,Nico,Hulkenberg,Nico Hulkenberg,...,20.0,,NaN,0 days 00:01:05.606000,NaT,NaT,NaT,,NaN,NaN

In [59]:
ses_res.columns

Index(['DriverNumber', 'BroadcastName', 'Abbreviation', 'DriverId', 'TeamName',
       'TeamColor', 'TeamId', 'FirstName', 'LastName', 'FullName',
       'HeadshotUrl', 'CountryCode', 'Position', 'ClassifiedPosition',
       'GridPosition', 'Q1', 'Q2', 'Q3', 'Time', 'Status', 'Points', 'Laps'],
      dtype='object')

In [60]:
# Display Clean Result
Q_result = slipclassify.clean_result(ses_res)
Q_result

   Abbreviation         TeamName  Position
4           NOR          McLaren       1.0
16          LEC          Ferrari       2.0
81          PIA          McLaren       3.0
44          HAM          Ferrari       4.0
63          RUS         Mercedes       5.0
30          LAW     Racing Bulls       6.0
1           VER  Red Bull Racing       7.0
5           BOR      Kick Sauber       8.0
12          ANT         Mercedes       9.0
10          GAS           Alpine      10.0
14          ALO     Aston Martin      11.0
23          ALB         Williams      12.0
6           HAD     Racing Bulls      13.0
43          COL           Alpine      14.0
87          BEA     Haas F1 Team      15.0
18          STR     Aston Martin      16.0
31          OCO     Haas F1 Team      17.0
22          TSU  Red Bull Racing      18.0
55          SAI         Williams      19.0
27          HUL      Kick Sauber      20.0

In [61]:
# Export Results of Quali
Q_result.to_csv("../data/Quali_Result.csv")

### Time Analysis

In [62]:
# Load lap data
Q_lap = session_Q.laps
Q_lap

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:23:14.776000,NOR,4,NaT,1.0,1.0,0 days 00:21:47.835000,NaT,NaT,0 days 00:00:38.857000,...,True,McLaren,0 days 00:21:47.835000,2025-06-28 14:09:26.637,1,NaN,False,,False,False
1,0 days 00:24:19.448000,NOR,4,0 days 00:01:04.672000,2.0,1.0,NaT,NaT,0 days 00:00:16.434000,0 days 00:00:28.843000,...,True,McLaren,0 days 00:23:14.776000,2025-06-28 14:10:53.578,1,NaN,False,,False,True
2,0 days 00:25:53.967000,NOR,4,0 days 00:01:34.519000,3.0,1.0,NaT,0 days 00:25:50.712000,0 days 00:00:27.082000,0 days 00:00:37.232000,...,True,McLaren,0 days 00:24:19.448000,2025-06-28 14:11:58.250,1,NaN,False,,False,False
3,0 days 00:32:14.682000,NOR,4,NaT,4.0,2.0,0 days 00:30:50.949000,NaT,NaT,0 days 00:00:38.018000,...,False,McLaren,0 days 00:25:53.967000,2025-06-28 14:13:32.769,1,NaN,False,,False,False
4,0 days 00:33:19.559000,NOR,4,0 days 00:01:04.877000,5.0,2.0,NaT,NaT,0 days 00:00:16.407000,0 days 00:00:28.763000,...,False,McLaren,0 days 00:32:14.682000,2025-06-28 14:19:53.484,1,NaN,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,0 days 00:29:22.752000,HUL,27,0 days 00:01:05.606000,5.0,2.0,NaT,NaT,0 days 00:00:16.581000,0 days 00:00:29.067000,...,False,Kick Sauber,0 days 00:28:17.146000,2025-06-28 14:15:55.948,1,NaN,False,,False,True
306,0 days 00:30:41.854000,HUL,27,0 days 00:01:19.102000,6.0,2.0,NaT,0 days 00:30:38.410000,0 days 00:00:18.124000,0 days 00:00:31.906000,...,False,Kick Sauber,0 days 00:29:22.752000,2025-06-28 14:17:01.554,1,NaN,False,,False,False
307,0 days 00:33:51.398000,HUL,27,NaT,7.0,3.0,0 days 00:32:16.554000,NaT,NaT,0 days 00:00:36.674000,...,True,Kick Sauber,0 days 00:30:41.854000,2025-06-28 14:18:20.656,1,NaN,False,,False,False
308,0 days 00:34:57.173000,HUL,27,0 days 00:01:05.775000,8.0,3.0,NaT,NaT,0 days 00:00:16.479000,0 days 00:00:29.455000,...,True,Kick Sauber,0 days 00:33:51.398000,2025-06-28 14:21:30.200,1,NaN,False,,False,True
309,0 days 00:36:27.970000,HUL,27,0 days 00:01:30.797000,9.0,3.0,NaT,0 days 00:36:24.626000,0 days 00:00:21.319000,0 days 00:00:38.404000,...,True,Kick Sauber,0 days 00:34:57.173000,2025-06-28 14:22:35.975,1,NaN,False,,False,False

In [63]:
# Fastest Lap
fastest_lap = Q_lap.pick_fastest()
fastest_lap

Time                      0 days 01:25:47.360000
Driver                                       NOR
DriverNumber                                   4
LapTime                   0 days 00:01:03.971000
LapNumber                                   17.0
Stint                                        6.0
PitOutTime                                   NaT
PitInTime                                    NaT
Sector1Time               0 days 00:00:16.285000
Sector2Time               0 days 00:00:28.436000
Sector3Time               0 days 00:00:19.250000
Sector1SessionTime        0 days 01:24:59.674000
Sector2SessionTime        0 days 01:25:28.110000
Sector3SessionTime        0 days 01:25:47.360000
SpeedI1                                    316.0
SpeedI2                                    252.0
SpeedFL                                    286.0
SpeedST                                    318.0
IsPersonalBest                              True
Compound                                    SOFT
TyreLife                                     2.0
FreshTyre                                   True
Team                                     McLaren
LapStartTime              0 days 01:24:43.389000
LapStartDate          2025-06-28 15:12:22.191000
TrackStatus                                   12
Position                                     NaN
Deleted                                    False
DeletedReason
FastF1Generated                            False
IsAccurate                                  True
Name: 16, dtype: object

In [64]:
# Make it pretty
pretty_fast = slipclassify.analyse_fastest(fastest_lap)
pretty_fast

        Name     Value
0     Driver       NOR
1  LapNumber      17.0
2    LapTime  1:03.971
3      Stint       6.0
4   Compound      SOFT

In [65]:
# Get the total lap, stint made by each driver
lap_stint_summary = slipclassify.get_lap_stint(Q_lap)
lap_stint_summary

   Driver  TotalLaps  TotalStint
0     NOR         18           6
1     LEC         21           7
2     PIA         19           6
3     HAM         21           7
4     RUS         18           6
5     LAW         17           6
6     VER         18           6
7     BOR         21           7
8     ANT         17           6
9     GAS         21           7
10    ALO         14           5
11    ALB         18           7
12    HAD         12           4
13    COL         15           5
14    BEA         15           5
15    STR          9           3
16    OCO          9           3
17    TSU          6           2
18    SAI         12           4
19    HUL          9           3

In [66]:
# Extract the data
lap_stint_summary.to_csv("../data/Quali_Lap_stint.csv")

In [67]:
# Analyse Fresh Tyre Period
ft_period = slipclassify.get_fresh_tyre_period(Q_lap)
ft_period

   Driver  TyrePeriod
5     LAW          15
2     PIA          13
3     HAM          12
0     NOR          12
13    COL          12
4     RUS          12
1     LEC           9
6     VER           9
9     GAS           9
10    ALO           9
12    HAD           9
7     BOR           9
18    SAI           9
15    STR           9
14    BEA           9
8     ANT           8
17    TSU           6
16    OCO           6
19    HUL           6
11    ALB           5

In [68]:
# Extract Data
ft_period.to_csv("../data/Fresh_Tyre_Period.csv",index=False)